### ISSUE TITLE
Set card size on deck import

### ISSUE THREAD

**Issue by moose2181** [brunocalado/mass-import#1]
This mod is awesome. It honestly has stopped me from returning Foundry VTT. I love the deck import feature. I am not a programmer, so I don't know how hard this would be to do. 

It would be awesome if the deck importer had a way to specify the dimensions of the cards that it is creating. Right now they seem to default to 100 px by 100 px and if I were to change that I would have to click on each card.

Thanks for the awesome mod!

**Comment by brunocalado** [comment]
done

**Comment by moose2181** [comment]
Thank you so much!!!!!!
