### ISSUE TITLE
Feature Request: Import Images as individual Journals

### ISSUE THREAD

**Issue by That-Italian-Guy** [brunocalado/mass-import#2]
Right now you can only mass import Images from a folder as either pages in a Journal or all images into one single text page.

It would be good to have the option to create a single Journal per image (with NameNNN for the structure, where NNN starts at 000 and it increases by +1 for each iteration).

This will allow the user to create a rollable table from the imported images - right now it is not possible as individual pages can't even be dragged into a Rollable table to use as content.

**Comment by brunocalado** [comment]
> Right now you can only mass import Images from a folder as either pages in a Journal or all images into one single text page.
> 
> It would be good to have the option to create a single Journal per image (with NameNNN for the structure, where NNN starts at 000 and it increases by +1 for each iteration).
> 
> This will allow the user to create a rollable table from the imported images - right now it is not possible as individual pages can't even be dragged into a Rollable table to use as content.

I can take a look, but the page to table is a better solution
https://github.com/foundryvtt/foundryvtt/issues/9088

**Comment by brunocalado** [comment]
done. update

**Comment by That-Italian-Guy** [comment]
> I can take a look, but the page to table is a better solution [foundryvtt/foundryvtt#9088](https://github.com/foundryvtt/foundryvtt/issues/9088)

Thanks for the super quick update! Dragging a page to the rollable table would unfortunately not work out well when you have to generate a large rollable table, like 100+ items. 

I've just tried your solution and it works like a charm! I can:
1. Create a folder with 100+ Journal entries from images with this module;
2. Export the folder structure to a Journal Compendium (with the Compendium Folder module);
3. Create a rollable table from the folder inside the Compendium;
4. Delete the folder with the 100+ Journal entries from the sidebar
And now I have a weightless random image generator with 100+ entries :)
