### ISSUE TITLE
cant mass import anymore

### ISSUE THREAD

**Issue by dosuserx** [brunocalado/mass-import#3]
this module worked until it didn't. now im getting a macro not connected error.

![screenshot 130](https://github.com/brunocalado/mass-import/assets/12874047/cb3d5deb-38cd-44f7-b006-02d2d35d5592)

i cant find any way to get more info about this issue.

**Comment by brunocalado** [comment]
> this module worked until it didn't. now im getting a macro not connected error.
> 
> ![screenshot 130](https://user-images.githubusercontent.com/12874047/248583778-cb3d5deb-38cd-44f7-b006-02d2d35d5592.jpg)
> 
> i cant find any way to get more info about this issue.

Do you have macro manager module?

Can you test in another world?

Can you paste the log?

**Comment by dosuserx** [comment]
first off, thank you for the hunt about trying it in another world with
macro manager, that worked.

ill begin layering on the mods i need until it disappears. one of the mods
i need must be interacting with it but mass import is a feature i only need
during world setup, if it disappears after i import all my pictures as
scenes that's no big a deal. when mass import disappears again, I'll send a
log.
