### ISSUE TITLE
Feature, add size to image, video import options...

### ISSUE THREAD

**Issue by jacksands** [brunocalado/mass-import#4]
Please add the option to alter de default size to the import options, for the images and videos in the journal to be smaller and easier to visualize...

and as always tks for the amazing work!

![image](https://github.com/brunocalado/mass-import/assets/7229143/0ceb6c63-d4a0-411c-94e6-af02ddc10af8)
![image](https://github.com/brunocalado/mass-import/assets/7229143/9d52d929-aca4-45ef-8bc1-8b6428d4d7d8)
![image](https://github.com/brunocalado/mass-import/assets/7229143/f9c0638a-52a5-41d8-a339-6288075cf775)

**Comment by brunocalado** [comment]
done, v12 only
