### ISSUE TITLE
[BUG] Can't mass import images from S3

### ISSUE THREAD

**Issue by carolinex** [brunocalado/mass-import#6]
When I try to import files from a folder in S3, I get the error shown in the image 
<img width="250" alt="image" src="https://github.com/user-attachments/assets/f484a3c1-8352-4342-ad9f-88e399d655f7">

Is there a way to make this work with S3? Thank you

**Comment by brunocalado** [comment]
Just glancing at your codebase, you've got 'data' hard-coded as the data location for your FilePicker to read/write.  You'll need to make that a bit more flexible to use s3 instead where appropriate
Lines like this
https://github.com/brunocalado/mass-import/blob/ed4322e7c77d508218bfb1cee6679c27625c11ff/scripts/scene-importer.js#L64

**Comment by brunocalado** [comment]
I don't have time to delve super deep into your code, but just from a quick glance you probably need to be getting the data source tab on the file browser when you grab the folder path and use that to pick what to browse.  `nav.tabs .active` will be the tab that's active, and `data-tab=` is where the tab string is stored.  It'll be `data` for user data, `public` for core data, and `s3` for any S3 bucket that's configured

**Comment by carolinex** [comment]
> I don't have time to delve super deep into your code, but just from a quick glance you probably need to be getting the data source tab on the file browser when you grab the folder path and use that to pick what to browse. `nav.tabs .active` will be the tab that's active, and `data-tab=` is where the tab string is stored. It'll be `data` for user data, `public` for core data, and `s3` for any S3 bucket that's configured

I forked the project but haven't done anything to it yet.  I might take a stab at adapting it as you mention.

(Btw, I was a little confused with "your code", isn't this your repo?)

**Comment by brunocalado** [comment]
> > I don't have time to delve super deep into your code, but just from a quick glance you probably need to be getting the data source tab on the file browser when you grab the folder path and use that to pick what to browse. `nav.tabs .active` will be the tab that's active, and `data-tab=` is where the tab string is stored. It'll be `data` for user data, `public` for core data, and `s3` for any S3 bucket that's configured
> 
> I forked the project but haven't done anything to it yet. I might take a stab at adapting it as you mention.
> 
> (Btw, I was a little confused with "your code", isn't this your repo?)

Sorry, I asked for help and these messages are the replies I received. I paste here to study it later.

**Comment by brunocalado** [comment]
> > I don't have time to delve super deep into your code, but just from a quick glance you probably need to be getting the data source tab on the file browser when you grab the folder path and use that to pick what to browse. `nav.tabs .active` will be the tab that's active, and `data-tab=` is where the tab string is stored. It'll be `data` for user data, `public` for core data, and `s3` for any S3 bucket that's configured
> 
> I forked the project but haven't done anything to it yet. I might take a stab at adapting it as you mention.
> 
> (Btw, I was a little confused with "your code", isn't this your repo?)

I don't really now how to fix this. I'll need help.

**Comment by carolinex** [comment]
I was able to make it work. Sent you a PR. 
BTW, are you brazilian? I am too, but living in Seattle.

**Comment by brunocalado** [comment]
> I was able to make it work. Sent you a PR. BTW, are you brazilian? I am too, but living in Seattle.

Sou sim, vou ver o seu merge. Mas, ele não afeta o funcionamento usual? Eu vi um módulo que tinha um opção para você ativar o uso de S3. Você ativava a opção se usasse S3

**Comment by brunocalado** [comment]
> Eu testei o funcionamento sem S3 e funcionou normal, pois o código só busca no S3 se "activeSource" for igual a "s3" no FilePicker. Se a pessoa não tiver s3, nem tem como esse valor estar na variável.
> 
> Não testei em versões anteriores do Foundry, só na v12, mas até onde sei o FilePicker não mudou da v11 pra v12. Até posso dar uma olhada no v11 no fim de semana, mas será uma instalação no computador local então não terá s3.

Naõ precisa, só v12 mesmo esse mod
